Parse link

diff --git a/.github/workflows/issue-ops.yml b/.github/workflows/issue-ops.yml
--- a/.github/workflows/issue-ops.yml
+++ b/.github/workflows/issue-ops.yml
@@ -182,12 +182,20 @@ jobs:
       - name: Creating Postman release
         id: create-release
         timeout-minutes: 5
+        outputs:
+            version_link: ${{ steps.create-release.outputs.version_link }}
         env:
           RELEASE_NAME: ${{ steps.validate_params.outputs.RELEASE_NAME }}
           RELEASE_NOTES: ${{ steps.validate_params.outputs.RELEASE_NOTES }}
         run: | 
-            export POSTMAN_API_ID=$(grep 'id =' .postman/api | cut -d' ' -f3)
-            postman api publish "${POSTMAN_API_ID}" --name "${RELEASE_NAME}" --api-definition "postman/schemas" --release-notes "${RELEASE_NOTES}" --collections postman/collections/*.json
+          export POSTMAN_API_ID=$(grep 'id =' .postman/api | cut -d' ' -f3)
+          publish_output=$(postman api publish "${POSTMAN_API_ID}" --name "${RELEASE_NAME}" --api-definition "postman/schemas" --release-notes "${RELEASE_NOTES}" --collections postman/collections/*.json 2>&1 | tee publish_output.txt)
+          version_link=$(grep -o 'https://go.postman.co/apis/[^"]*' publish_output.txt)
+          if [ -z "$version_link" ]; then
+            echo "Failed to extract version link from publish output"
+            exit 1
+          fi
+          echo "version_link=$version_link" >> $GITHUB_OUTPUT
 
       - name: Create release succeeded
         id: pm-release-succeeded
@@ -206,6 +214,7 @@ jobs:
             ### Postman release created successfully :tada:
 
             * :seedling: __Release-Name__: ${RELEASE_NAME}
+            * :link: __Version-Link__: ${{ steps.create-release.outputs.version_link }}
 
             <details>
             
